language: go

go:
  - tip
  - "1.14.3"
  - "1.13.11"
  - "1.12.17"
  - "1.11.13"
  - "1.10.8"
  - "1.9.7"
  - "1.8.7"
  - "1.7.6"
  - "1.6.4"

matrix:
  allow_failures:
    - go: tip

script: make test
